service: upx-sls-api-apiName
provider:
  name: aws
  runtime: python3.7
  vpc:
    securityGroupIds:
      - sg-0f4b1287f9f690fea
    subnetIds:
      - subnet-03692d93cc69db081
      - subnet-004299ac81d4b8c0d
  stage: dev
  region: us-east-1
  apiName: ${self:service}-api
  stackName: ${self:service}-cloudformation
  memorySize: 128
  role: arn:aws:iam::069272698867:role/lambda_demos
  deploymentBucket:
    name: upaxer-serverless-api
    versioning: true
plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-deployment-bucket
  - serverless-domain-manager
package:
  exclude:
    - venv/**
    - package-lock.json
    - package.json
    - node_modules/**
custom:
  wsgi:
    app: app.app
    packRequirements: false
  domain:
    app: apisls.upaxdev.com
    admin: adminsls.upaxdev.com
  customDomain:
    domainName: ${self:custom.domain.${opt:stage}}
    basePath: path
    stage: ${self:provider.stage}
    certificateName: '*.upaxdev.com'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
functions:
  app:
    name: ${self:service}
    handler: wsgi_handler.handler
    description: API Services for UPAX, Path /user_info
    memorySize: 512
    timeout: 30
    layers:
      - arn:aws:lambda:us-east-1:069272698867:layer:cx-oracle-layer:12
      - arn:aws:lambda:us-east-1:069272698867:layer:flask-layer:3
    vpc:
      securityGroupIds:
        - sg-0f4b1287f9f690fea
      subnetIds:
        - subnet-03692d93cc69db081
        - subnet-004299ac81d4b8c0d
    events:
      - http:
          method: any
          path: /{proxy+}
          cors: true
